component:
  name: project_default_service_account_add_role
  template:
    resource:
      null_resource:
        project_default_service_account_add_role:
          triggers:
            project_id: '${data.terraform_remote_state.project_default.project_id}'
            service_account_name: >-
              ${data.terraform_remote_state.project_default_service_account.service_account_name}
          provisioner:
            - local-exec:
                when: create
                command: 'python ${local.component["path"]}/scripts/apply.py'
                environment:
                  project_id: '${data.terraform_remote_state.project_default.project_id}'
                  service_account_name: >-
                    ${data.terraform_remote_state.project_default_service_account.service_account_name}
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default_service_account_add_role/terraform.tfstate
    data:
      terraform_remote_state:
        project_default:
          backend: local
          config:
            path: >-
              /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default/terraform.tfstate
        project_default_service_account:
          backend: local
          config:
            path: >-
              /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default_service_account/terraform.tfstate
  dependsOn:
    - ../project_default
    - ../project_default_service_account
    - ../project_default_service_account_key
    - ../project_default_service_enable
