component:
  name: modul
  template:
    data:
      local_file:
        output_file:
          depends_on: [null_resource.modul_output]
          filename: ${path.module}/output.json
    resource:
      null_resource:
        modul:
          triggers:
            command: '${var.command}'
            components: '${md5(jsonencode(var.components))}'
          provisioner:
            - local-exec:
                when: create
                command: 'python ${local.component["path"]}/scripts/apply.py'
                environment:
                  root: '${local.project["path"]}'
                  command: '${var.command}'
                  components: '${jsonencode(var.components)}'
        modul_output:
          depends_on: [null_resource.modul]
          triggers:
            timestamp: '${timestamp()}'
          provisioner:
            - local-exec:
                command: 'python ${local.component["path"]}/scripts/output.py'
                environment:
                  root: '${local.project["path"]}'
                  components: '${jsonencode(var.components)}'
    output:
      info:
        value: ${data.local_file.output_file.content}
    variable:
      command:
        type: string
      components:
        type: map
    tfvars:
      command: apply
      components:
        # project_default: s3://data-lake-terrahub-us-east-1/AWSLogs/tfvars/terraform-google-project-factory/project_dafault/default.tfvars
        # project_default_service_account: s3://data-lake-terrahub-us-east-1/AWSLogs/tfvars/terraform-google-project-factory/project_dafault/default.tfvars
        # project_default_service_account_add_role: s3://data-lake-terrahub-us-east-1/AWSLogs/tfvars/terraform-google-project-factory/project_dafault/default.tfvars
        # project_default_service_account_key: s3://data-lake-terrahub-us-east-1/AWSLogs/tfvars/terraform-google-project-factory/project_dafault/default.tfvars
        # project_default_service_enable: s3://data-lake-terrahub-us-east-1/AWSLogs/tfvars/terraform-google-project-factory/project_dafault/default.tfvars
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-google-project-factory/modul/terraform.tfstate
