## local config
component:
  name: project_default_service_account_key
  dependsOn:
    - ../project_default
    - ../project_default_service_account
  template:
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default_service_account_key/terraform.tfstate
    data:
      terraform_remote_state:
        project_default:
          backend: local
          config:
          - path: /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default/terraform.tfstate
        project_default_service_account:
          backend: local
          config:
          - path: /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default_service_account/terraform.tfstate
    resource:
      null_resource:
        project_default_service_account_key:
          triggers:
            project_id: ${data.terraform_remote_state.project_default.project_id}
            service_account_name: ${data.terraform_remote_state.project_default_service_account.service_account_name}
            file_path: ${var.file_path}
          provisioner:
            - local-exec:
                when: create
                command: 'python ${local.component["path"]}/scripts/apply.py'
                environment:
                  project_id: ${data.terraform_remote_state.project_default.project_id}
                  service_account_name: ${data.terraform_remote_state.project_default_service_account.service_account_name}
                  file_path: ${var.file_path}
            - local-exec:
                when: destroy
                command: echo ${var.file_path}
    output:
      file_path:
        value: ${var.file_path}
    variable:
      file_path:
        type: string
        description: File path
        default: /tmp/.google/terraform_google_access.json
