component:
  name: project_default_service_account_key
  template:
    resource:
      null_resource:
        project_default_service_account_key:
          triggers:
            project_id: '${data.terraform_remote_state.project_default.project_id}'
            service_account_name: >-
              ${data.terraform_remote_state.project_default_service_account.service_account_name}
            file_path: '${var.project_default_service_account_key_file_path}'
          provisioner:
            - local-exec:
                when: create
                command: 'python ${local.component["path"]}/scripts/apply.py'
                environment:
                  project_id: '${data.terraform_remote_state.project_default.project_id}'
                  service_account_name: >-
                    ${data.terraform_remote_state.project_default_service_account.service_account_name}
                  file_path: '${var.project_default_service_account_key_file_path}'
    output:
      file_path:
        value: '${var.project_default_service_account_key_file_path}'
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default_service_account_key/terraform.tfstate
    data:
      terraform_remote_state:
        project_default:
          backend: local
          config:
            path: >-
              /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default/terraform.tfstate
        project_default_service_account:
          backend: local
          config:
            path: >-
              /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default_service_account/terraform.tfstate
    tfvars:
      project_default_service_account_key_file_path: /tmp/.google/terraform_google_access.json
  dependsOn:
    - ../project_default
    - ../project_default_service_account
