component:
  name: project_default_service_enable
  template:
    resource:
      null_resource:
        project_default_service_enable:
          triggers:
            project_id: '${data.terraform_remote_state.project_default.project_id}'
            service_name: '${var.project_default_service_enable_service_name}'
          provisioner:
            - local-exec:
                when: create
            - local-exec:
                command: 'python ${local.component["path"]}/scripts/apply.py'
            - local-exec:
                environment:
                  project_id: '${data.terraform_remote_state.project_default.project_id}'
            - local-exec:
                environment:
                  service_name: '${var.project_default_service_enable_service_name}'
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default_service_enable/terraform.tfstate
    data:
      terraform_remote_state:
        project_default:
          backend: local
          config:
            path: >-
              /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default/terraform.tfstate
    variable:
      project_default_service_enable_service_name:
        type: string
  dependsOn:
    - ../project_default
