## local config
component:
  name: project_default_service_enable
  dependsOn:
    - ../project_default
  template:
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default_service_enable/terraform.tfstate
    data:
      terraform_remote_state:
        project_default:
          backend: local
          config:
          - path: /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default/terraform.tfstate
    resource:
      null_resource:
        project_default_service_enable:
          triggers:
            project_id: ${data.terraform_remote_state.project_default.project_id}
            service_name: ${var.service_name}
          provisioner:
            - local-exec:
                when: create
                command: 'python ${local.component["path"]}/scripts/apply.py'
                environment:
                  project_id: ${data.terraform_remote_state.project_default.project_id}
                  service_name: ${var.service_name}
            - local-exec:
                when: destroy
                command: echo ${var.service_name}
    variable:
      service_name:
        type: string
        description: Service Name
        default: cloudresourcemanager.googleapis.com
