project:
  name: terraform-google-project-factory
  code: 1a370f85
  include:
    - .
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'
terraform:
  varFile:
    - default.tfvars
  version: 0.11.11
