## local config
component:
  name: project_default
  template:
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/terraform-google-project-factory/project_default/terraform.tfstate
    locals:
      project_name: ${var.project_name}
      project_id: ${format("%s-%s",var.project_name, random_id.random_project_id_suffix.hex)}
    resource:
      random_id:
        random_project_id_suffix:
          byte_length: 4
      null_resource:
        project_default:
          triggers:
            project_id: ${local.project_id}
            organization_id: ${var.organization_id}
          provisioner:
            - local-exec:
                when: create
                command: 'python ${local.component["path"]}/scripts/apply.py'
                environment:
                  project_name: ${local.project_name}
                  project_id: ${local.project_id}
                  organization_id: ${var.organization_id}
            - local-exec:
                when: destroy
                command: echo ${local.project_name}
    output:
      project_name:
        value: ${local.project_name}
      project_id:
        value: ${local.project_id}
      organization_id:
        value: ${var.organization_id}
    variable:
      project_name:
        type: string
        description: Project name
        default: terraform-factory
      organization_id:
        type: string
        description: Organization Id
        default: ''
      