component:
  name: factory
  template:
    data:
      external:
        factory_output_file:
          depends_on:
            - null_resource.factory
          program:
            - cat
            - '${path.module}/output.json'
    resource:
      null_resource:
        factory:
          triggers:
            command: '${var.factory_command}'
            components: '${md5(jsonencode(var.factory_components))}'
            timestamp: '${timestamp()}'
          provisioner:
            - local-exec:
                command: 'python ${local.component["path"]}/scripts/apply.py'
                environment:
                  root: '${local.project["path"]}'
                  command: '${var.factory_command}'
                  components: '${jsonencode(var.factory_components)}'
    output:
      factory:
        value: '${data.external.factory_output_file.result}'
    variable:
      factory_command:
        type: string
        default: run
      factory_components:
        type: map
    tfvars:
      factory_components:
        project_default: >-
          s3://data-lake-terrahub-us-east-1/AWSLogs/tfvars/terraform-google-project-factory/project_default/default.tfvars
        project_default_service_account: >-
          s3://data-lake-terrahub-us-east-1/AWSLogs/tfvars/terraform-google-project-factory/project_default_service_account/default.tfvars
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-google-project-factory/factory/terraform.tfstate
