component:
  name: lien
  template:
    resource:
      google_resource_manager_lien:
        lien:
          parent: 'projects/${data.terraform_remote_state.project.thub_id}'
          restrictions: '${var.lien_restrictions}'
          origin: '${var.lien_origin}'
          reason: '${var.lien_reason}'
          count: '${var.lien ? 1 : 0}'
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-google-project-factory/lien/terraform.tfstate
    data:
      terraform_remote_state:
        project:
          backend: local
          config:
            path: >-
              /tmp/.terrahub/local_backend/terraform-google-project-factory/project/terraform.tfstate
    # variable:
    #   lien:
    #     type: string
    #   lien_restrictions:
    #     type: list
    #   lien_origin:
    #     type: string
    #   lien_reason:
    #     type: string
    tfvars:
      lien: false
      lien_restrictions: []
      lien_origin: ''
      lien_reason: ''
  dependsOn:
    - ../project
