## local config
component:
  name: lien
  dependsOn:
    - ../project
  template:
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/local_backend/terraform-google-project-factory/lien/terraform.tfstate
    data:
      terraform_remote_state:
        project:
          backend: local
          config:
          - path: /tmp/.terrahub/local_backend/terraform-google-project-factory/project/terraform.tfstate
    resource:
      google_resource_manager_lien:
        lien:
          count: ${var.lien ? 1 : 0}
          parent: projects/${data.terraform_remote_state.project.thub_id}
          restrictions: ${var.lien_restrictions}
          origin: ${var.lien_origin}
          reason: ${var.lien_reason}
    output:
      name:
        value: '${google_resource_manager_lien.lien.name}'
      create_time:
        value: '${google_resource_manager_lien.lien.create_time}'
    variable:
      lien:
        type: bool
      lien_project_id:
        type: string
      lien_restrictions:
        type: list
      lien_origin:
        type: string
      lien_reason:
        type: string
        default: This project is an important environment

