component:
  name: project_services_use_modul
  template:
    resource:
      google_project_service:
        project_services_use_modul:
          service: '${element(var.project_services_activate_apis, count.index)}'
          count: '${length(var.project_services_activate_apis)}'
          project: '${data.terraform_remote_state.project_modul.modul["project_id"]}'
          disable_on_destroy: '${var.project_services_disable_services_on_destroy}'
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-google-project-factory/project_services_use_modul/terraform.tfstate
    tfvars:
      project_services_activate_apis: ["iam.googleapis.com"]
      project_services_disable_services_on_destroy: true
    data:
      terraform_remote_state:
        project_modul:
          backend: local
          config:
            path: >-
              /tmp/.terrahub/local_backend/terraform-google-project-factory/modul/terraform.tfstate
  # dependsOn:
  #   - ../../.terrahub/modul
